// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOnILkWneOdqiyTShyE_BEzjV1H6x6P5A',
    appId: '1:467430495661:web:e1e2b59fb3e94beb793d24',
    messagingSenderId: '467430495661',
    projectId: 'appcmdes',
    authDomain: 'appcmdes.firebaseapp.com',
    databaseURL: 'https://appcmdes-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'appcmdes.appspot.com',
    measurementId: 'G-5FTJ2HZ4C1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm5XL5oGzL1WkcUh7JSbEUXoX6AD7rYeM',
    appId: '1:467430495661:android:9065ffd391303f16793d24',
    messagingSenderId: '467430495661',
    projectId: 'appcmdes',
    databaseURL: 'https://appcmdes-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'appcmdes.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOnILkWneOdqiyTShyE_BEzjV1H6x6P5A',
    appId: '1:467430495661:web:2d95e1c8fc0c96e1793d24',
    messagingSenderId: '467430495661',
    projectId: 'appcmdes',
    authDomain: 'appcmdes.firebaseapp.com',
    databaseURL: 'https://appcmdes-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'appcmdes.appspot.com',
    measurementId: 'G-RFD14R3900',
  );

}